# Generated by Django 5.1.3 on 2024-12-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0004_review_offer_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='offer_detail_id',
        ),
    ]
