# Generated by Django 5.1.3 on 2024-12-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder_app", "0007_alter_review_offer_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="review",
            name="offer",
        ),
    ]
