# Generated by Django 5.1.3 on 2024-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coder_app", "0013_alter_review_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
