# Generated by Django 5.1.3 on 2024-12-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0015_remove_businessprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='file',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
