# Generated by Django 5.1.3 on 2024-12-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0016_remove_businessprofile_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='profile_image',
            new_name='file',
        ),
    ]
