# Generated by Django 5.1.3 on 2024-12-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder_app", "0018_rename_file_businessprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="date_of_birth",
        ),
    ]
