# Generated by Django 5.1.3 on 2024-12-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder_app", "0020_remove_businessprofile_company_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessprofile",
            old_name="profile_image",
            new_name="file",
        ),
    ]
