# Generated by Django 5.1.3 on 2024-12-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0022_rename_image_offer_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='profile_image',
            new_name='file',
        ),
    ]
