# Generated by Django 5.1.3 on 2024-12-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder_app", "0024_rename_file_offer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerdetail",
            name="additional_details",
        ),
    ]
